services :
  app:
    build:
    ports:
      - "3000:3000"
      volumes:
        - .:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

db:
  image: postgres:12
  environnement:
    postgres_users: postgres
    postgres_password: postgres
    postgres_db: postgres